---
- hosts: leaf1-DC1, leaf2-DC2
  gather_facts: no
  tasks: 
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay-DCs.yml"
      name: underlay
  - name: Create interface configurations 
    template: # This is Jinja right here, and we pass "vars" into Jinja
      src: "{{lookup('env','PWD')}}/templates/interfaces.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"
  - name: Upload configs
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_interface.cfg"
      save_when: modified