---
- hosts: leafs_DC1, leafs_DC2
  gather_facts: no
  connection: local
  tasks:
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/vlans.j2"
      dest: "{{lookup('env','PWD')}}/configs/vlans_{{inventory_hostname}}.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/vlans_{{inventory_hostname}}.cfg"


