- hosts: all
  gather_facts: no
  connection: local
  tasks: 
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay-DCs.yml"
      name: underlay
  - name: Report IPs for all devices
    template:
      src: "{{lookup('env','PWD')}}/templates/IP_report.j2"
      dest: "{{lookup('env','PWD')}}/reports/{{inventory_hostname}}_IP_report.txt"